enableInlineHunks: true

packageExtensions:
  eslint-config-airbnb@*:
    # Все эти зависимости являются опциональными, что упущено в package.json у eslint-config-airbnb
    peerDependenciesMeta:
      eslint-plugin-import:
        optional: true
      eslint-plugin-jsx-a11y:
        optional: true
      eslint-plugin-react:
        optional: true
      eslint-plugin-react-hooks:
        optional: true
  next@*:
    # Бабель добавляет core-js во внутренние модули некста
    dependencies:
      core-js: ^3
  styled-components@*:
    # react-is является peerDependency (как и react), мы не хотим её указывать
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
